name: ELA
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.6.1
  cached_network_image: ^3.2.3
  image_picker: ^0.8.4+4
  image_picker_web: ^2.1.1
  intl: ^0.17.0
  uuid: ^3.0.7
  shared_preferences: ^2.1.1
  share_plus: ^10.0.0
  url_launcher: ^6.1.10
  flutter_local_notifications: ^9.1.5
  chewie: ^1.3.0
  file_picker: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
